llm:
  api_key: 
  base_url: https://api.deepseek.com
  model: deepseek-chat
  type: maas
log:
  level: INFO
project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '5'
  language: zh
  namespace: RiskMining
  
lf_solver_pipeline:
  reasoner:
    lf_planner:
      type: base
      logic_form_plan_prompt:
        type: riskmining_lf_plan
        
vectorize_model: &vectorize_model_config
  type: mock
  vector_dimensions: 768

vectorizer:
  type: batch
  vectorize_model: *vectorize_model_config
