llm: &id001
  api_key: key
  base_url: https://api.deepseek.com
  model: deepseek-chat
  type: maas
log:
  level: INFO
project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '4'
  language: zh
  namespace: RiskMining
vectorize_model: &id002
  type: mock
  vector_dimensions: 768
vectorizer:
  type: batch
  vectorize_model: *id002


lf_solver_pipeline:
  memory: default_memory
  max_iterations: 3
  generator:
    type: default_generator
    generate_prompt:
      type: resp_riskmining
  reflector:
    type: default_reflector
  reasoner:
    type: default_reasoner
    lf_planner:
      logic_form_plan_prompt:
        type: riskmining_lf_plan
      type: default_lf_planner
    lf_executor:
      type: default_lf_executor
      force_chunk_retriever: true
      exact_kg_retriever:
        type: default_exact_kg_retriever
        el_num: 1
        search_api: &id003
          type: openspg_search_api
        graph_api: &id004
          type: openspg_graph_api
      fuzzy_kg_retriever:
        type: default_fuzzy_kg_retriever
        el_num: 1
        vectorize_model: *id002
        llm_client: *id001
        search_api: *id003
        graph_api: *id004
      chunk_retriever: &id005
        type: default_chunk_retriever
        recall_num: 10
        rerank_topk: 10
      merger:
        type: default_lf_sub_query_res_merger
        chunk_retriever: *id005