project:
  biz_scene: medical
  namespace: Medicine
  host_addr: http://127.0.0.1:8887
  language: zh
  id: 4


vectorize_model: &vectorize_model_config
  type: mock
  vector_dimensions: 768

vectorizer:
  type: batch
  vectorize_model: *vectorize_model_config


llm: &llm_conf  
  api_key: key
  base_url: https://api.deepseek.com
  model: deepseek-chat
  type: maas

log:
  level: INFO


spg_runner:
  reader:
    type:
      csv
  chain:
    type: structured
    mapping:
      type: spg
    writer:
      type: kg
  ckpt_dir: ./spg-runner-ckpt
  
spo_runner:
  reader:
    type:
      csv
  chain:
    type: structured
    mapping:
      type: spo
      s_id_col: S
      p_type_col: P
      o_id_col: O
      sub_property_col: properties

    writer:
      type: kg
  ckpt_dir: ./spo-runner-ckpt

extract_runner:
  num_parallel: 10
  reader:
    type:
      csv
  chain:
    type: unstructured
    parser:
      type: dict
      id_col: idx
      name_col: title
      content_col: text
    splitter:
      split_length: 100000
      type: length
      window_length: 0    
    extractor:
      llm: *llm_conf
      ner_prompt:
        type: example_medical_ner
      std_prompt:
        type: example_medical_std
      triple_prompt:
        type: example_medical_triple
      type: kag
    vectorizer:
      type: batch
      vectorize_model: *vectorize_model_config
    writer:
      type: kg
  ckpt_dir: ./extract-runner-ckpt   
  
 
lf_solver_pipeline:
  generator:
    generate_prompt:
      type: example_resp_generator
  reasoner:
    lf_solver:
      kg_retriever:
        type: base
      chunk_retriever:
        type: kag
        ner_prompt:
          type: example_medical_question_ner
    
