extract_runner:
  chain:
    extractor:
      llm: &id001
        api_key: key
        base_url: https://api.deepseek.com
        model: deepseek-chat
        type: maas
      ner_prompt:
        type: example_medical_ner
      std_prompt:
        type: example_medical_std
      triple_prompt:
        type: example_medical_triple
      type: kag
    parser:
      content_col: text
      id_col: idx
      name_col: title
      type: dict
    splitter:
      split_length: 100000
      type: length
      window_length: 0
    type: unstructured
    vectorizer:
      type: batch
      vectorize_model: &id002
        api_key: key
        base_url: https://api.siliconflow.cn/v1/
        model: BAAI/bge-large-en-v1.5
        type: openai
        vector_dimensions: 1024
    writer:
      type: kg
  num_parallel: 10
  reader:
    type: csv
lf_solver_pipeline:
  generator:
    generate_prompt:
      type: example_resp_generator
  reasoner:
    lf_solver:
      chunk_retriever:
        ner_prompt:
          type: example_medical_question_ner
        type: kag
      kg_retriever:
        type: base
llm: *id001
log:
  level: INFO
project:
  biz_scene: medical
  host_addr: http://127.0.0.1:8887
  id: '3'
  language: zh
  namespace: Medicine
  checkpoint_path: ./extract-runner-ckpt
  
spg_runner:
  chain:
    mapping:
      type: spg
    type: structured
    writer:
      type: kg
  reader:
    type: csv
spo_runner:
  chain:
    mapping:
      o_id_col: O
      p_type_col: P
      s_id_col: S
      sub_property_col: properties
      type: spo
    type: structured
    writer:
      type: kg
  reader:
    type: csv
vectorize_model: *id002
vectorizer:
  type: batch
  vectorize_model: *id002
