project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  language: en
  namespace: HotpotQA
  id: 3


vectorize_model: &vectorize_model_config
  path: ~/.cache/vectorizer/BAAI/bge-base-en-v1.5
  type: bge
  vector_dimensions: 768


llm: &llm_conf  
  api_key: key
  base_url: https://api.deepseek.com
  model: deepseek-chat
  type: maas

log:
  level: INFO

runner:
  num_parallel: 10
  reader:
    type:
      hotpotqa
  chain:
    type: unstructured
    extractor:
      llm: *llm_conf
      ner_prompt:
        type: hotpotqa_ner
      std_prompt:
        type: hotpotqa_std
      triple_prompt:
        type: hotpotqa_triple
      type: kag
    parser:
      type: dict
    splitter:
      split_length: 100000
      type: length
      window_length: 0
    vectorizer:
      type: batch
      vectorize_model: *vectorize_model_config
    post_processor:
      type: base
      similarity_threshold: 0.9
    writer:
      type: kg
    
lf_solver_pipeline:
  generator:
    generate_prompt:
      type: resp_simple
      
resp_solver_pipeline:
  generator:
    generate_prompt:
      type: resp_simple
  reasoner:
    lf_planner:
      type: empty
    lf_solver:
      kg_retriever: null
      chunk_retriever:
        type: kag
    
