llm: &id001
  api_key: key
  base_url: https://api.deepseek.com
  model: deepseek-chat
  type: maas
log:
  level: INFO
project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '2'
  language: zh
  namespace: BaiKe
resp_solver_pipeline:
  generator:
    generate_prompt:
      type: resp_simple
  reasoner:
    lf_planner:
      type: empty
    lf_solver:
      chunk_retriever:
        type: kag
      kg_retriever: null
runner:
  chain:
    extractor:
      llm: *id001
      ner_prompt:
        type: spg_entity
      event_prompt:
        type: spg_event
      std_prompt:
        type: default_std
      relation_prompt:
        type: spg_relation
      type: schema_constraint
    reader:
      type: txt
    post_processor:
      similarity_threshold: 0.9
      type: base
    splitter:
      split_length: 300
      type: length
      window_length: 0
    type: unstructured
    vectorizer:
      type: batch
      vectorize_model: &id002
        api_key: key
        base_url: https://api.siliconflow.cn/v1/
        model: BAAI/bge-m3
        type: openai
        vector_dimensions: 1024
    writer:
      type: kg
  num_threads_per_chain: 2
  num_chains: 4      
  scanner:
    type: dir
vectorize_model: *id002
vectorizer: *id002
qa:
  force_chunk_retriever: true
